import type { KeywordId } from '../syntax';

/**
 * Keywords are part of the algorithm, not of the interface: they follow the
 * "Pseudocode language" setting, never the app language, so an algorithm reads
 * the same on every device.
 */
export type KeywordLanguage = 'en' | 'pt-BR';

export type KeywordTable = Record<KeywordId, string>;

export const KEYWORD_LANGUAGES: readonly KeywordLanguage[] = ['en', 'pt-BR'];

export const KEYWORDS: Record<KeywordLanguage, KeywordTable> = {
	en: {
		algorithm: 'Algorithm',
		if: 'if',
		then: 'then',
		elseif: 'else if',
		else: 'else',
		endif: 'end if',
		for: 'for',
		forall: 'for all',
		foreach: 'for each',
		do: 'do',
		endfor: 'end for',
		while: 'while',
		endwhile: 'end while',
		loop: 'loop',
		endloop: 'end loop',
		repeat: 'repeat',
		until: 'until',
		procedure: 'procedure',
		endprocedure: 'end procedure',
		function: 'function',
		endfunction: 'end function',
		upon: 'upon',
		endupon: 'end upon',
		switch: 'switch',
		case: 'case',
		otherwise: 'otherwise',
		begin: 'begin',
		end: 'end',
		return: 'return',
		print: 'print',
		break: 'break',
		continue: 'continue',
		require: 'Require',
		ensure: 'Ensure',
		input: 'Input',
		output: 'Output',
		data: 'Data',
		result: 'Result',
		and: 'and',
		or: 'or',
		not: 'not',
		true: 'true',
		false: 'false',
		to: 'to',
		downto: 'downto',
	},
	'pt-BR': {
		algorithm: 'Algoritmo',
		if: 'se',
		then: 'então',
		elseif: 'senão se',
		else: 'senão',
		endif: 'fim se',
		for: 'para',
		forall: 'para todo',
		foreach: 'para cada',
		do: 'faça',
		endfor: 'fim para',
		while: 'enquanto',
		endwhile: 'fim enquanto',
		loop: 'laço',
		endloop: 'fim laço',
		repeat: 'repita',
		until: 'até que',
		procedure: 'procedimento',
		endprocedure: 'fim procedimento',
		function: 'função',
		endfunction: 'fim função',
		upon: 'ao ocorrer',
		endupon: 'fim ao ocorrer',
		switch: 'escolha',
		case: 'caso',
		otherwise: 'outro caso',
		begin: 'início',
		end: 'fim',
		return: 'retorne',
		print: 'imprima',
		break: 'interrompa',
		continue: 'continue',
		require: 'Requer',
		ensure: 'Garante',
		input: 'Entrada',
		output: 'Saída',
		data: 'Dados',
		result: 'Resultado',
		and: 'e',
		or: 'ou',
		not: 'não',
		true: 'verdadeiro',
		false: 'falso',
		to: 'até',
		downto: 'decrescendo até',
	},
};
